### ISSUE TITLE
Unable to add more than one fabric

### ISSUE THREAD

**Issue by herver** [infiniband-radar/infiniband-radar-web#13]
Hi there,

I'm evaluating the project (build from `7c368e016a5742d6e1f7f9ecf62c4e335544ec53`) and it works very well so far, but I'm having problems when trying to insert a second fabric (named `fabric-qcd` for now), the following exception is thrown by the API server:

```
api_1       | [Wed, 15 Jan 2020 10:28:55 GMT][INFO][TopologyDatabase] [fabric-qcd] Set default topology to timestamp '1579084133178'   
api_1       | (node:16) UnhandledPromiseRejectionWarning: MongoError: Cannot change the size of a document in a capped collection: 41 != 61
api_1       |     at Function.create (/home/node/server/node_modules/mongodb/lib/core/error.js:44:12)                                  
api_1       |     at toError (/home/node/server/node_modules/mongodb/lib/utils.js:150:22)                                               
api_1       |     at coll.s.topology.update (/home/node/server/node_modules/mongodb/lib/operations/common_functions.js:373:39)         
api_1       |     at handler (/home/node/server/node_modules/mongodb/lib/core/sdam/topology.js:973:24)                                  
api_1       |     at wireProtocol.(anonymous function) (/home/node/server/node_modules/mongodb/lib/core/sdam/server.js:437:5)          
api_1       |     at /home/node/server/node_modules/mongodb/lib/core/connection/pool.js:420:18                                          
api_1       |     at process._tickCallback (internal/process/next_tick.js:61:11)                                                       
api_1       | (node:16) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
api_1       | (node:16) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I tried looking around in the code but my Mongo and TypeScript skills are close to `nil`. Am I missing something to get a second fabric to push data in the `radar` ?

**Comment by carstenpatzke** [comment]
Hey,
thanks for using InfiniBand-Radar.

I'm using a simple map/dictionary/_object_ to store the fabricId next to a timestamp which indicates the default version (used in the compare tool).

The database is limited to just one entry and initialized here: https://github.com/infiniband-radar/infiniband-radar-web/blob/7c368e016a5742d6e1f7f9ecf62c4e335544ec53/server/src/services/TopologyDatabase.ts#L48-L54

Unfortunately the stack trace is not helpful so my guess is that in this line an error occurs when trying to update _this_ database object.

https://github.com/infiniband-radar/infiniband-radar-web/blob/7c368e016a5742d6e1f7f9ecf62c4e335544ec53/server/src/services/TopologyDatabase.ts#L166-L168


Do you see some kind of warning like "No default timestamps are available!" at the start of the web-api-server?

**Comment by herver** [comment]
Hello,

Thank you for your reply, we do not see any warning related to the timestamp when starting the `web-api` server:

```
api_1       | > infiniband-radar-api-server@2.4.3 start /home/node/server
api_1       | > ts-node src/Server.ts
api_1       |
api_1       | (node:22) ExperimentalWarning: The fs.promises API is experimental
api_1       | [Mon, 03 Feb 2020 09:42:16 GMT][INFO][MetricDatabase] Created database 'infiniband_radar'
api_1       | [Mon, 03 Feb 2020 09:42:16 GMT][INFO][MetricDatabase] Creating retention policy 'rp_14d' for database 'infiniband_radar'
api_1       | [Mon, 03 Feb 2020 09:42:17 GMT][INFO][MetricDatabase] Created retention policy 'rp_14d' for database 'infiniband_radar'
api_1       | [Mon, 03 Feb 2020 09:42:17 GMT][INFO][MetricDatabase] [fabric-qcd] Updating global metric
api_1       | [Mon, 03 Feb 2020 09:42:17 GMT][INFO][MetricDatabase] [fabric-be] Updating global metric
api_1       | [Mon, 03 Feb 2020 09:42:17 GMT][INFO][TopologyDatabase] Setup 'mongodb://mongodb:27017/infiniband_radar'
api_1       | [Mon, 03 Feb 2020 09:42:17 GMT][INFO][TopologyDatabase] Update default topologies cache
api_1       | [Mon, 03 Feb 2020 09:42:17 GMT][INFO][TopologyDatabase] Fetch last snapshot for 'fabric-qcd'
api_1       | [Mon, 03 Feb 2020 09:42:17 GMT][INFO][TopologyDatabase] Update change overview for 'fabric-qcd'
api_1       | [Mon, 03 Feb 2020 09:42:17 GMT][INFO][TopologyDatabase] Fetch last snapshot for 'fabric-be'
api_1       | [Mon, 03 Feb 2020 09:42:17 GMT][WARN][TopologyDatabase] 'fabric-be' has never provided a topology! Is the daemon running?
api_1       | [Mon, 03 Feb 2020 09:42:17 GMT][INFO][UserDatabase] Setup 'mongodb://mongodb:27017/infiniband_radar'
api_1       | [Mon, 03 Feb 2020 09:42:17 GMT][INFO][Server] Database setup complete
api_1       | [Mon, 03 Feb 2020 09:42:17 GMT][INFO][Server] Server startup complete
api_1       | [Mon, 03 Feb 2020 09:42:17 GMT][INFO][Server] API Server is listening on http://0.0.0.0:4201/
```
After, when trying to push metrics for the 2nd fabric it fails because its topology couldn't be uploaded.

I tried to update the TopologyDatabase schema (https://github.com/infiniband-radar/infiniband-radar-web/blob/7c368e016a5742d6e1f7f9ecf62c4e335544ec53/server/src/services/TopologyDatabase.ts#L52) to remove the "only one entry" limit, but with no luck...

**Comment by carstenpatzke** [comment]
In general the limit should be at 1 to prevent data inconsistency.
This one document is able to store multiple fabrics.

Maybe we can find the error manually otherwise we might have to delete this table (which only contains default timestamps and is not that important).
```sh
docker exec -it infiniband-radar-web_mongodb_1 mongo infiniband_radar --eval "db.topologyDefaultTimestamp.find()"
```

If successful, I would expect to see just one line like this:
```json
{ "_id" : ObjectId("4bb317bc56d30ba341bc3f78"), "fabric-be" : 1570453303118 }
```
with two fabrics it would look like this:
```json
{ "_id" : ObjectId("4bb317bc56d30ba341bc3f78"), "fabric-be" : 1570453303118, "fabric-qcd" : 157045312313 }
```
If there is just one I would also like to check the table settings:
``` sh
docker exec -it infiniband-radar-web_mongodb_1 mongo infiniband_radar --eval "db.topologyDefaultTimestamp.stats()"
```

Since this output tends to be a little verbose, you should format it with a collapsible block.
```
<details><summary>CLICK ME</summary>
<p>
\```
Your output
\```
</p>
</details>
```
without `\`

**Comment by herver** [comment]
Here's the output of the various commands...

```
# docker exec -it infiniband-radar-web_mongodb_1 mongo infiniband_radar --eval "db.topologyDefaultTimestamp.find()"
MongoDB shell version v4.1.2
connecting to: mongodb://127.0.0.1:27017/infiniband_radar
MongoDB server version: 4.1.2
{ "_id" : ObjectId("5e37eeb55b46c5e7a1b4e4c1"), "fabric-qcd" : 1580723890986 }
```

As there's only one document returned, here's the output of the last command:
<details><summary>CLICK ME</summary>
<p>
```
[root@hroussea-build01 infiniband-radar-web]# docker exec -it infiniband-radar-web_mongodb_1 mongo infiniband_radar --eval "db.topologyDefaultTimestamp.stats()"                                                                                                                                                                                                    [110/150]
MongoDB shell version v4.1.2                           
connecting to: mongodb://127.0.0.1:27017/infiniband_radar
MongoDB server version: 4.1.2
{                          
        "ns" : "infiniband_radar.topologyDefaultTimestamp",   
        "size" : 42,                                
        "count" : 1,                                     
        "avgObjSize" : 42,                                     
        "storageSize" : 16384,                                                             
        "capped" : true,                                     
        "max" : 32,                                                      
        "maxSize" : 2097152,                                               
        "sleepCount" : 0,                                                           
        "sleepMS" : 0,                                                     
        "wiredTiger" : {                                                    
                "metadata" : {                         
                        "formatVersion" : 1                                                  
                },                                                                                           
                "creationString" : "access_pattern_hint=none,allocation_size=4KB,app_metadata=(formatVersion=1),assert=(commit_timestamp=none,read_timestamp=none),block_allocation=best,block_compressor=snappy,cache_resident=false,checksum=on,colgroups=,collator=,columns=,dictionary=0,encryption=(keyid=,name=),exclusive=false,extractor=,format=btree,huffman_key=,h
uffman_value=,ignore_in_memory_cache_size=false,immutable=false,internal_item_max=0,internal_key_max=0,internal_key_truncate=true,internal_page_max=4KB,key_format=q,key_gap=10,leaf_item_max=0,leaf_key_max=0,leaf_page_max=32KB,leaf_value_max=64MB,log=(enabled=true),lsm=(auto_throttle=true,bloom=true,bloom_bit_count=16,bloom_config=,bloom_hash_count=8,bloom_oldest=
false,chunk_count_limit=0,chunk_max=5GB,chunk_size=10MB,merge_custom=(prefix=,start_generation=0,suffix=),merge_max=15,merge_min=0),memory_page_image_max=0,memory_page_max=10m,os_cache_dirty_max=0,os_cache_max=0,prefix_compression=false,prefix_compression_min=4,source=,split_deepen_min_child=0,split_deepen_per_child=0,split_pct=90,type=file,value_format=u",
                "type" : "file",                                                 
                "uri" : "statistics:table:collection-9--5806714067978286191",
                "LSM" : {                                                
                        "bloom filter false positives" : 0,
                        "bloom filter hits" : 0,     
                        "bloom filter misses" : 0,                 
                        "bloom filter pages evicted from cache" : 0,
                        "bloom filter pages read into cache" : 0,
                        "bloom filters in the LSM tree" : 0, 
                        "chunks in the LSM tree" : 0,                      
                        "highest merge generation in the LSM tree" : 0,
                        "queries that could have benefited from a Bloom filter that did not exist" : 0,
                        "sleep for LSM checkpoint throttle" : 0,   
                        "sleep for LSM merge throttle" : 0,                         
                        "total size of bloom filters" : 0                       
                },                                           
                "block-manager" : {                       
                        "allocations requiring file extension" : 3,
                        "blocks allocated" : 3,                             
                        "blocks freed" : 0,                    
                        "checkpoint size" : 4096,     
                        "file allocation unit size" : 4096,
                        "file bytes available for reuse" : 0,
                        "file magic number" : 120897,                                                                  
                        "file major version number" : 1,
                        "file size in bytes" : 16384,
                        "minor version number" : 0
                },
                "btree" : {
                        "btree checkpoint generation" : 1733,
                        "column-store fixed-size leaf pages" : 0,
                        "column-store internal pages" : 0,
                        "column-store variable-size RLE encoded values" : 0,
                        "column-store variable-size deleted values" : 0,
                        "column-store variable-size leaf pages" : 0,
                        "fixed-record size" : 0,
                        "maximum internal page key size" : 368,
                        "maximum internal page size" : 4096,
                        "maximum leaf page key size" : 2867,
                        "maximum leaf page size" : 32768,
                        "maximum leaf page value size" : 67108864,
                        "maximum tree depth" : 3,
                        "number of key/value pairs" : 0,
                        "overflow pages" : 0,
                        "pages rewritten by compaction" : 0,
                        "row-store internal pages" : 0,
                        "row-store leaf pages" : 0
                },
                "cache" : {
                        "bytes currently in the cache" : 1134,
                        "bytes read into cache" : 0,
                        "bytes written from cache" : 136,
                        "checkpoint blocked page eviction" : 0,
                        "data source pages selected for eviction unable to be evicted" : 0,
                        "eviction walk passes of a file" : 0,
                        "eviction walk target pages histogram - 0-9" : 0,
                        "eviction walk target pages histogram - 10-31" : 0,
                        "eviction walk target pages histogram - 128 and higher" : 0,
                        "eviction walk target pages histogram - 32-63" : 0,
                        "eviction walk target pages histogram - 64-128" : 0,
                        "eviction walks abandoned" : 0,
                        "eviction walks gave up because they restarted their walk twice" : 0,
                        "eviction walks gave up because they saw too many pages and found no candidates" : 0,
                        "eviction walks gave up because they saw too many pages and found too few candidates" : 0,
                        "eviction walks reached end of tree" : 0,                                                                                                                                                                                                                                                                                                    [24/150]
                        "eviction walks started from root of tree" : 0,
                        "eviction walks started from saved location in tree" : 0,
                        "hazard pointer blocked page eviction" : 0,
                        "in-memory page passed criteria to be split" : 0,
                        "in-memory page splits" : 0,
                        "internal pages evicted" : 0,
                        "internal pages split during eviction" : 0,
                        "leaf pages split during eviction" : 0,
                        "modified pages evicted" : 0,
                        "overflow pages read into cache" : 0,
                        "page split during eviction deepened the tree" : 0,
                        "page written requiring lookaside records" : 0,
                        "pages read into cache" : 0,
                        "pages read into cache after truncate" : 1,
                        "pages read into cache after truncate in prepare state" : 0,
                        "pages read into cache requiring lookaside entries" : 0,
                        "pages requested from the cache" : 2,
                        "pages seen by eviction walk" : 0,
                        "pages written from cache" : 2,
                        "pages written requiring in-memory restoration" : 0,
                        "tracked dirty bytes in the cache" : 0,
                        "unmodified pages evicted" : 0
                },
                "cache_walk" : {
                        "Average difference between current eviction generation when the page was last considered" : 0,
                        "Average on-disk page image size seen" : 0,
                        "Average time in cache for pages that have been visited by the eviction server" : 0,
                        "Average time in cache for pages that have not been visited by the eviction server" : 0,
                        "Clean pages currently in cache" : 0,
                        "Current eviction generation" : 0,
                        "Dirty pages currently in cache" : 0,
                        "Entries in the root page" : 0,
                        "Internal pages currently in cache" : 0,
                        "Leaf pages currently in cache" : 0,
                        "Maximum difference between current eviction generation when the page was last considered" : 0,
                        "Maximum page size seen" : 0,
                        "Minimum on-disk page image size seen" : 0,
                        "Number of pages never visited by eviction server" : 0,
                        "On-disk page image sizes smaller than a single allocation unit" : 0,
                        "Pages created in memory and never written" : 0,
                        "Pages currently queued for eviction" : 0,
                        "Pages that could not be queued for eviction" : 0,
                        "Refs skipped during cache traversal" : 0,
                        "Size of the root page" : 0,
                        "Total number of pages currently in cache" : 0
                },
                "compression" : {
                        "compressed pages read" : 0,
                        "compressed pages written" : 0,
                        "page written failed to compress" : 0,
                        "page written was too small to compress" : 2,
                        "raw compression call failed, additional data available" : 0,
                        "raw compression call failed, no additional data available" : 0,
                        "raw compression call succeeded" : 0
                },
                "cursor" : {
                        "bulk-loaded cursor-insert calls" : 0,
                        "create calls" : 3,
                        "cursor operation restarted" : 0,
                        "cursor-insert key and value bytes inserted" : 43,
                        "cursor-remove key bytes removed" : 0,
                        "cursor-update value bytes updated" : 0,
                        "cursors cached on close" : 0,
                        "cursors reused from cache" : 2,
                        "insert calls" : 1,
                        "modify calls" : 0,
                        "next calls" : 4,
                        "prev calls" : 1,
                        "remove calls" : 0,
                        "reserve calls" : 0,
                        "reset calls" : 10,
                        "search calls" : 0,
                        "search near calls" : 0,
                        "truncate calls" : 0,
                        "update calls" : 0
                },
                "reconciliation" : {
                        "dictionary matches" : 0,
                        "fast-path pages deleted" : 0,
                        "internal page key bytes discarded using suffix compression" : 0,
                        "internal page multi-block writes" : 0,
                        "internal-page overflow keys" : 0,
                        "leaf page key bytes discarded using prefix compression" : 0,
                        "leaf page multi-block writes" : 0,
                        "leaf-page overflow keys" : 0,
                        "maximum blocks required for a page" : 1,
                        "overflow values written" : 0,
                        "page checksum matches" : 0,
                        "page reconciliation calls" : 2,
                        "page reconciliation calls for eviction" : 0,
                        "pages deleted" : 0
                },
                "session" : {
                        "cached cursor count" : 3,
                        "object compaction" : 0,
                        "open cursor count" : 0
                },
                "transaction" : {
                        "update conflicts" : 0
                }
        },
        "nindexes" : 1,
        "totalIndexSize" : 16384,
        "indexSizes" : {
                "_id_" : 16384
        },
        "ok" : 1
}
```
</p>
</details>

Hope it helps...

I've deleted the mongodb data files (and all of the data in fact) multiple times, but the behaviour described here is reproducible everytime.

**Comment by carstenpatzke** [comment]
Oh wow, I am a little bit embarrassed.
It seems that somehow during the setup of our infiniband-radar instance and the publication on GitHub I've somehow changed the way the database is created.
**Our collection is not capped!**

In the [official documentation](https://docs.mongodb.com/manual/reference/method/db.collection.updateOne/#capped-collection) it even says that an update on a capped collection will causes an error.

I really don't know how this happened, sorry.

Hopefully this is fixed in the [newest release](https://github.com/infiniband-radar/infiniband-radar-web/releases).
See the release notes and the README.md for update tips.

**Comment by herver** [comment]
Nice catch !

I was puzzled indeed because on some screenshots I saw from presentations given about the tool there was clearly support for more that one fabric :)

Updating to the latest version `2.4.4` and updating the schema worked beautifully:

```
api_1       | [Wed, 05 Feb 2020 06:01:08 GMT][INFO][TopologiesController] [fabric-be] Got first topology version
api_1       | [Wed, 05 Feb 2020 06:01:08 GMT][Debug][ApiServer] Took 38 ms to process (PUT) '/api/v2/topologies/fabric-be' StatusCode: 204
api_1       | [Wed, 05 Feb 2020 06:01:08 GMT][INFO][TopologyOptimizerService] [fabric-be] Start optimization
api_1       | [Wed, 05 Feb 2020 06:01:10 GMT][INFO][TopologyOptimizerService] [fabric-be] Optimization took 2563ms
api_1       | [Wed, 05 Feb 2020 06:01:10 GMT][INFO][TopologyDatabase] [fabric-be] Set default topology to timestamp '1580882468342'
api_1       | [Wed, 05 Feb 2020 06:01:10 GMT][INFO][TopologyDatabase] Update change overview for 'fabric-be'
```

Thanks for the great work :rocket: !
